### ISSUE TITLE
Install language pack failed

### ISSUE THREAD

**Issue by younthu** [louismullie/treat#115]
I tried to install english pack, 

~~~

Treat::Core::Installer.install 'english'

~~~

failed with errors below:

~~~
3. Downloading models for the Punkt segmenter for the English language.

RuntimeError: Couldn't download http://www.louismullie.com/treat/punkt/english.yaml (Max number of attempts reached). Error: (Operation timed out - connect(2) for "www.louismullie.com" port 80)

~~~

Does anyone has the same issue?  It seems the language package host is down now, anyone can help on this please?

Is there anyway for manual installation of those language packages?

**Comment by naltun** [comment]
I am having the same issue. I would love to see/assist in a solution for this. :+1:

**Comment by cherniv** [comment]
I do see it too. I have Ruby version 2.1.5p273

**Comment by markoblad** [comment]
Similar on the stanford-core-nlp-all.zip and all the JAR links: http://louismullie.com/treat/stanford-core-nlp-minimal.zip and http://louismullie.com/treat/stanford-core-nlp-english.zip and http://louismullie.com/treat/stanford-core-nlp-all.zip

3. Download Stanford Core NLP JARs and model files for the the English language.

RuntimeError: Couldn't download http://www.louismullie.com/treat/stanford-core-nlp-all.zip (Max number of attempts reached). Error: (getaddrinfo: nodename nor servname provided, or not known)

**Comment by pawandubey** [comment]
Still getting this error. Unable to install on Ubuntu 14.04 and ruby 2.2.3

**Comment by NickLamping** [comment]
Thanks to @garside for this solution.

**If you are having this issue:**

Navigate to

    ~/.rvm/gems/ruby-X.Y.Z/gems/treat-A.B.C/lib/treat/core/installer.rb

And change line 8 from

    Server = 'www.louismullie.com'
to

    Server = 's3.amazonaws.com/static-public-assets'

**Comment by cunger** [comment]
Same for me: 
```
RuntimeError: Couldn't download http://www.louismullie.com/treat/punkt/english.yaml (Max number of attempts reached). Error: (Response code was not 200 , but 502.)
```

**Comment by Levenade** [comment]
For me as well.  www.louismullie.com is down entirely.  Is there an alternate location to download the required files manually?

**Comment by garside** [comment]
Navigate to `~/.rvm/gems/ruby-X.Y.Z/gems/treat-A.B.C/lib/treat/core/installer.rb`

And change line 8 from:

`Server = 'www.louismullie.com'`

to:

`Server = 's3.amazonaws.com/static-public-assets'`

**Comment by NickLamping** [comment]
Is there any chance someone has the Reuters models too? Those files are also on `www.louismullie.com` and that website is down.

**Comment by louismullie** [comment]
The server that was holding the files suffered a total loss of data, and I have no backup. As shown by how old this thread is, I have no time to fix this issue either.

If one of you can fix up a package containing the right files and send a link by e-mail I promise to upload it to the new server.

**Comment by naltun** [comment]
@louismullie Thanks, man! :+1:  Good guy, Louis.

**Comment by delgiudices** [comment]
I changed the server to aws but i still can't download the spanish language, is there a way i can do this manually?

**Comment by drusepth** [comment]
Is there any workaround like the above to get this gem working again on apps running on Heroku?

**Comment by NickLamping** [comment]
I don't have an answer for the previous commenter but for posterity's sake I'm going to leave a link to a JavaScript library that you can actually use and contains many of the features that this gem once had.

[NLP Compromise](https://github.com/nlp-compromise/nlp_compromise)

**Comment by drusepth** [comment]
To answer my above question, I went ahead and just forked `treat` and made @garside's change in the gem itself. You can use the modified version of the gem that uses his mirrors by changing the Gemfile to point at that forked git repo, with
```
gem 'treat', :git => 'https://github.com/indentlabs/treat-gem.git'
```

**Comment by philhartmanonic** [comment]
@drusepth I've been getting an error:
`RuntimeError: Couldn't download http://s3.amazonaws.com/static-public-assets/treat/punkt/english.yaml (Max number of attempts reached). Error: (wrong number of arguments (given 2, expected 0))
	from /home/rotten/.rvm/gems/ruby-2.3.1/gems/schiphol-1.0.1/lib/schiphol.rb:138:in `rescue in download'
	from /home/rotten/.rvm/gems/ruby-2.3.1/gems/schiphol-1.0.1/lib/schiphol.rb:147:in `download'
	from /home/rotten/.rvm/gems/ruby-2.3.1/gems/treat-2.1.0/lib/treat/core/installer.rb:149:in `download_punkt_models'
	from /home/rotten/.rvm/gems/ruby-2.3.1/gems/treat-2.1.0/lib/treat/core/installer.rb:55:in `install'
	from (irb):2
	from /home/rotten/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
`

**Comment by philhartmanonic** [comment]
@drusepth I keep getting this error:
```RuntimeError: Couldn't download http://s3.amazonaws.com/static-public-assets/treat/punkt/english.yaml (Max number of attempts reached). Error: (wrong number of arguments (given 2, expected 0))
	from /home/rotten/.rvm/gems/ruby-2.3.1/gems/schiphol-1.0.1/lib/schiphol.rb:141:in `rescue in download'
	from /home/rotten/.rvm/gems/ruby-2.3.1/gems/schiphol-1.0.1/lib/schiphol.rb:150:in `download'
	from /home/rotten/.rvm/gems/ruby-2.3.1/gems/treat-2.1.0/lib/treat/core/installer.rb:149:in `download_punkt_models'
	from /home/rotten/.rvm/gems/ruby-2.3.1/gems/treat-2.1.0/lib/treat/core/installer.rb:55:in `install'
	from (irb):26

**Comment by psychoslave** [comment]
see https://github.com/louismullie/treat/issues/124
