### ISSUE TITLE
The installer is failing on 3rd step involving Punkt

### ISSUE THREAD

**Issue by mwlang** [louismullie/treat#123]
2.2.4 :002 > Treat::Core::Installer.install

Treat Installer, v. 2.1.0

1. Installing core dependencies.

Installing nokogiri...
Building native extensions.  This could take a while...
Installing ferret...
Building native extensions.  This could take a while...
Installing bson_ext...
Building native extensions.  This could take a while...
Installing mongo...
Building native extensions.  This could take a while...
Installing lda-ruby...
Building native extensions.  This could take a while...
Installing stanford-core-nlp...
Building native extensions.  This could take a while...
Installing linguistics...
This library also presents tie-ins for the 'linkparser' and
'wordnet' libraries, which you can enable by installing the
gems of the same name.
Installing ruby-readability...
Installing whatlanguage...
Installing chronic...
Installing kronic...
Installing nickel...
Installing decisiontree...
Installing rb-libsvm...
Building native extensions.  This could take a while...
Installing ruby-fann...
Building native extensions.  This could take a while...
Installing zip...
Installing loggability...
Installing tf-idf-similarity...
Installing narray...
Building native extensions.  This could take a while...
Installing fastimage...
Installing fuzzy-string-match...
Installing levenshtein-ffi...
Building native extensions.  This could take a while...

2. Installing dependencies for the English language.

Installing rbtagger...
Building native extensions.  This could take a while...
Installing ruby-stemmer...
Building native extensions.  This could take a while...
Installing punkt-segmenter...
Installing tactful_tokenizer...
Installing nickel...
Installing rwordnet...
Installing uea-stemmer...
Installing engtagger...
Installing activesupport...
Installing srx-english...
Installing scalpel...

3. Downloading models for the Punkt segmenter for the English language.

RuntimeError: Couldn't download http://www.louismullie.com/treat/punkt/english.yaml (Max number of attempts reached). Error: (Couldn't download https://coreslicer.com/treat/punkt/english.yaml (Max number of attempts reached). Error: (Response code was not 200 , but 404.))
	from /Users/mwlang/.rvm/gems/ruby-2.2.4/gems/schiphol-1.0.1/lib/schiphol.rb:138:in `rescue in download'
	from /Users/mwlang/.rvm/gems/ruby-2.2.4/gems/schiphol-1.0.1/lib/schiphol.rb:147:in `download'
	from /Users/mwlang/.rvm/gems/ruby-2.2.4/gems/treat-2.1.0/lib/treat/core/installer.rb:149:in `download_punkt_models'
	from /Users/mwlang/.rvm/gems/ruby-2.2.4/gems/treat-2.1.0/lib/treat/core/installer.rb:55:in `install'
	from (irb):2
	from /Users/mwlang/.rvm/rubies/ruby-2.2.4/bin/irb:11:in `<main>'
2.2.4 :003 >

**Comment by markwatneyy** [comment]
I was able to get step 3 to work by building from source with changes suggested @drusepth\'s PR
#120

**Comment by nevware** [comment]
http://www.louismullie.com/treat/punkt/english.yaml - it appears the site is entirely offline. 
Can the YAML files be hosted on Github instead?

**Comment by cincospenguinos** [comment]
I agree with nevware. Why aren't these static files hosted within the repo?

**Comment by rushilagr** [comment]
Guys this repo has not been maintained since quite a while. Just go through
the recent issues.

I tried to manually procure the required files but couldn't make it work.

Do let us know if you figure it out.

**Comment by an-nasir** [comment]
Facing same issue, the site with that english.yaml doesn't even load in browser.
Is there alternate cdn?

**Comment by an-nasir** [comment]
@samantharachelb can you post what steps you took to make this work?
