### ISSUE TITLE
undefined method `children' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by gabro** [louismullie/treat#65]
I'm trying to parse a document, but I get this error. Here's my code attempt

```
require 'treat'
include Treat::Core::DSL

rovio_privacy = document 'http://www.rovio.com/privacy'
rovio_privacy.apply :chunk, :segment, :tokenize, :parse
```

And here's the stacktrace

```
/Users/gabro/.rvm/gems/ruby-1.9.3-p448/gems/treat-2.0.7/lib/treat/core/dsl.rb:17:in `method_missing': undefined method `children' for nil:NilClass (NoMethodError)
    from /Users/gabro/.rvm/gems/ruby-1.9.3-p448/gems/treat-2.0.7/lib/treat/workers/processors/parsers/stanford.rb:57:in `recurse'
    from /Users/gabro/.rvm/gems/ruby-1.9.3-p448/gems/treat-2.0.7/lib/treat/workers/processors/parsers/stanford.rb:50:in `parse'
    from /Users/gabro/.rvm/gems/ruby-1.9.3-p448/gems/treat-2.0.7/lib/treat/entities/entity/delegatable.rb:66:in `call_worker'
    from /Users/gabro/.rvm/gems/ruby-1.9.3-p448/gems/treat-2.0.7/lib/treat/entities/entity/delegatable.rb:40:in `block (2 levels) in add_workers'
    from /Users/gabro/.rvm/gems/ruby-1.9.3-p448/gems/treat-2.0.7/lib/treat/entities/entity/applicable.rb:41:in `do_task'
    from /Users/gabro/.rvm/gems/ruby-1.9.3-p448/gems/treat-2.0.7/lib/treat/entities/entity/applicable.rb:49:in `block in do_task'
    from /Users/gabro/.rvm/gems/ruby-1.9.3-p448/gems/treat-2.0.7/lib/treat/entities/entity/applicable.rb:48:in `each'
    from /Users/gabro/.rvm/gems/ruby-1.9.3-p448/gems/treat-2.0.7/lib/treat/entities/entity/applicable.rb:48:in `do_task'
    from /Users/gabro/.rvm/gems/ruby-1.9.3-p448/gems/treat-2.0.7/lib/treat/entities/entity/applicable.rb:49:in `block in do_task'
    from /Users/gabro/.rvm/gems/ruby-1.9.3-p448/gems/treat-2.0.7/lib/treat/entities/entity/applicable.rb:48:in `each'
    from /Users/gabro/.rvm/gems/ruby-1.9.3-p448/gems/treat-2.0.7/lib/treat/entities/entity/applicable.rb:48:in `do_task'
    from /Users/gabro/.rvm/gems/ruby-1.9.3-p448/gems/treat-2.0.7/lib/treat/entities/entity/applicable.rb:49:in `block in do_task'
    from /Users/gabro/.rvm/gems/ruby-1.9.3-p448/gems/treat-2.0.7/lib/treat/entities/entity/applicable.rb:48:in `each'
    from /Users/gabro/.rvm/gems/ruby-1.9.3-p448/gems/treat-2.0.7/lib/treat/entities/entity/applicable.rb:48:in `do_task'
    from /Users/gabro/.rvm/gems/ruby-1.9.3-p448/gems/treat-2.0.7/lib/treat/entities/entity/applicable.rb:22:in `block in apply'
    from /Users/gabro/.rvm/gems/ruby-1.9.3-p448/gems/treat-2.0.7/lib/treat/entities/entity/applicable.rb:6:in `each'
    from /Users/gabro/.rvm/gems/ruby-1.9.3-p448/gems/treat-2.0.7/lib/treat/entities/entity/applicable.rb:6:in `apply'
    from test.rb:10:in `<main>'
```

I used the automatic installer and manually installed Enju, which is in my PATH.

Any idea on why I'm getting such error?

**Comment by dstarh** [comment]
Getting this same error, did anyone find a solution yet?

**Comment by cheerfulstoic** [comment]
I ended up using https://github.com/louismullie/stanford-core-nlp directly

**Comment by dstarh** [comment]
@cheerfulstoic I just downloaded that myself

**Comment by ojak** [comment]
Same issue.  I can get Stanford Core NLP running on my machine, but unfortunately I can't get Treat to parse on either 1.9.3 or 2.1.4.

Here's what I'm seeing:

    2.1.4 :001 > require 'treat'
    2.1.4 :002 > sent = "This is an English sentence, prove it to me!"
    2.1.4 :003 > sent.apply(:parse).print_tree
    NoMethodError: undefined method `children' for nil:NilClass
    from ~/.rvm/gems/ruby-2.1.4@nlp/gems/treat-2.1.0/lib/treat/workers/processors/parsers/stanford.rb:57:in `recurse'
    ~/.rvm/gems/ruby-2.1.4@nlp/gems/treat-2.1.0/lib/treat/workers/processors/parsers/stanford.rb @ line 50 Treat::Workers::Processors::Parsers::Stanford.parse:

Specifically, I think the failure occurs a little further up the chain at `Treat::Workers::Processors::Parsers::Stanford#parse` on line 48-49 of `stanford.rb`:

    48:  text = parser.apply(list)
    49:  recurse(text.children[0], entity, tag_set)

Since `parser.apply(list)` returns `nil`, calling `text.children` results in the `undefined method 'children' for nil:NilClass`.

I'm unclear whether it's a problem with the `list` variable or whether it's something that's occurring in either the `bind-it` or `rjb` gems what sending the data to the parser.  Any ideas why `parser.apply(list)` would be returning `nil`?

**Comment by ojak** [comment]
Ok, so this is interesting.  If I tokenize first, then parsing appears to be working.  For example:

**FAILS:**
Calling `parse` directly on the string.
```
2.1.4 :001 > 'This is an English sentence, prove it to me!'.parse.print_tree
NoMethodError: undefined method `children' for nil:NilClass
from ~/.rvm/gems/ruby-2.1.4@nlp/gems/treat-2.1.0/lib/treat/workers/processors/parsers/stanford.rb:57:in `recurse'
```

**WORKS:**
Adding `tokenize` before the `parse` method.
```
2.1.4 :001 > 'This is an English sentence, prove it to me!'.tokenize.parse.print_tree
+ Sentence (70142349342820)  --- "This is an [...] to me!"  ---  {:tag_set=>:penn}   --- []
|
+--+ Phrase (70142349274320)  --- "This"  ---  {:tag=>"NP"}   --- []
...
+--> Punctuation (70142352605260)  --- "!"  ---  {:tag=>"."}   --- [
```

Not sure why, but that seems to work.

**Comment by louismullie** [comment]
@ojak - indeed, as per the manual the parser requires tokenization. However it seems like the OP was appropriately tokenizing the sentences and still running into issues.

**Comment by ojak** [comment]
@louismullie - I see, so the OP's problem is different from the others (and mine).

FYI, I was also unable to reproduce the OP's error on ruby 2.1.4, treat 2.1.0, and stanford-core-nlp 0.5.1 with the complete JAR installed under RVM.

**Comment by ojak** [comment]
@gabro @acrookston - Does `stanford-core-nlp` work for you outside of treat?  From IRB, can you run the following without receiving an error (to ensure that the JAR's are in the right place):
```
2.1.4 :001 > require 'stanford-core-nlp'
2.1.4 :002 > pipeline = StanfordCoreNLP.load(:tokenize, :ssplit, :pos, :lemma, :parse, :ner, :dcoref)
```

**Comment by maccman** [comment]
Seeing this issue too.

**Comment by tbbooher** [comment]
same here
```
sent.apply(:parse).print_tree
NoMethodError: undefined method `children' for nil:NilClass
	from /Users/christinebooher/.rvm/gems/ruby-2.2.2@improvement.rocks/gems/treat-2.1.0/lib/treat/core/dsl.rb:17:in `method_missing'
	from /Users/christinebooher/.rvm/gems/ruby-2.2.2@improvement.rocks/gems/treat-2.1.0/lib/treat/workers/processors/parsers/stanford.rb:57:in `recurse'
```

**Comment by psychoslave** [comment]
I had the same problem, and preforming tokenization before parsing did resolved the problem. That makes sense as a pipeline, but as is the documentation doesn't explain it. On the contrary, it propose the example which was pasted here several time which skip the tokenization. 

The code should seamlessly run `tokenize` if needed and possible when the entity is parsed, so the documentation would be correct. Or an other option would be to let the documentation as is and catch this kind of exception when attempting to parse and throw relevant information about the mandatoriness of tokenizing before parsing.
