### ISSUE TITLE
LoadError: cannot load such file -- treat

### ISSUE THREAD

**Issue by peddinti** [louismullie/treat#98]
Hi, i have install the gem file but in IRB when i say require 'treat', i am getting the following error

LoadError: cannot load such file -- treat
	from /Users/ViswaMani/.rvm/gems/ruby-2.0.0-p451@futura/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
	from /Users/ViswaMani/.rvm/gems/ruby-2.0.0-p451@futura/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/ViswaMani/.rvm/gems/ruby-2.0.0-p451@futura/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/ViswaMani/.rvm/gems/ruby-2.0.0-p451@futura/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
	from (irb):1
	from /Users/ViswaMani/.rvm/gems/ruby-2.0.0-p451@futura/gems/railties-3.2.13/lib/rails/commands/console.rb:47:in `start'
	from /Users/ViswaMani/.rvm/gems/ruby-2.0.0-p451@futura/gems/railties-3.2.13/lib/rails/commands/console.rb:8:in `start'
	from /Users/ViswaMani/.rvm/gems/ruby-2.0.0-p451@futura/gems/railties-3.2.13/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'

**Comment by yanismydj** [comment]
I'm having the same problem with ruby 2.0.0 and Rails 4.1.6

**Comment by louismullie** [comment]
Do you have "treat" in your Gemfile?

**Comment by yanismydj** [comment]
Yes
